<?php
/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="footer">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                 <?= $block->getLayout()->getBlock('PageBuilderRenderer')->setIdentifier('section-423166')->toHtml(); ?> 
            </div>
        </div>
            <div class="col-md-3">
                <div class="row">
                    <h4><?= $block->escapeHtml(__('Your Account')) ?></h4>
                    <form class="form subscribe"
                        novalidate
                        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                        method="post"
                        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                        id="footer-newsletter-form">
                        <div class="field newsletter">
                            <div class="control">
                                <input type="email"
                                    name="email"
                                    placeholder="<?= $block->escapeHtml(__('Enter Email Address')) ?>"
                                    data-mage-init='{"mage/trim-input":{}}'
                                    data-validate="{required:true, 'validate-email':true}" />
                                <button type="submit" aria-label="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>">
                                    <img src="<?= $block->getViewFileUrl('images/send_icon.png'); ?>" alt="img" class="img-fluid">
                                </button>
                            </div>
                        </div>
                    </form>
                    <p class="update_text">
                        <?= $block->escapeHtml(__('Register now to get updates on promotions & coupons.')) ?>
                    </p>
                </div>
            </div>

            <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Customer/js/block-submit-on-send": {
                        "formId": "footer-newsletter-form"
                    }
                }
            }
            </script>

        </div>
    </div>
</div>
